
import React, { useState, useEffect, useMemo } from 'react';
import { db } from '../../db/mockDb';
import { useAuth } from '../../context/AuthContext';
import { Asset, AssetStatus, AppSettings } from '../../types';
import { Search, Archive, FileText, Calendar, User, DollarSign, Filter, ChevronDown, Download, Eye, X, Loader2, ShieldAlert } from 'lucide-react';

const RemovedAssetsRegister: React.FC = () => {
  const { user } = useAuth();
  const [removedAssets, setRemovedAssets] = useState<Asset[]>([]);
  const [settings, setSettings] = useState<AppSettings>(db.getSettings());
  const [searchTerm, setSearchTerm] = useState('');
  const [categoryFilter, setCategoryFilter] = useState('ALL');
  const [statusFilter, setStatusFilter] = useState('ALL');
  const [showDetail, setShowDetail] = useState<Asset | null>(null);
  const [isExporting, setIsExporting] = useState(false);

  useEffect(() => {
    const data = db.getAssets().filter(a => a.status === AssetStatus.REMOVED);
    setRemovedAssets(data.sort((a, b) => {
        const dateA = a.removalData?.removalTimestamp ? new Date(a.removalData.removalTimestamp).getTime() : 0;
        const dateB = b.removalData?.removalTimestamp ? new Date(b.removalData.removalTimestamp).getTime() : 0;
        return dateB - dateA;
    }));
  }, []);

  const categories = useMemo(() => ['ALL', ...new Set(removedAssets.map(a => a.assetType))], [removedAssets]);
  const statuses = useMemo(() => ['ALL', ...new Set(removedAssets.map(a => a.removalData?.statusToCheck || ''))], [removedAssets]);

  const filtered = removedAssets.filter(a => {
    const matchesSearch = a.assetCode.toLowerCase().includes(searchTerm.toLowerCase()) || 
                          a.brand.toLowerCase().includes(searchTerm.toLowerCase()) ||
                          a.model.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesCategory = categoryFilter === 'ALL' || a.assetType === categoryFilter;
    const matchesStatus = statusFilter === 'ALL' || a.removalData?.statusToCheck === statusFilter;
    return matchesSearch && matchesCategory && matchesStatus;
  });

  const canRead = user?.permissions?.rar?.read === true;

  const handleExportAll = async () => {
    if (filtered.length === 0) {
      alert("No archived assets available to export.");
      return;
    }
    if (!canRead) return;

    setIsExporting(true);
    try {
      const { jsPDF } = await import('jspdf');
      const autoTableModule = await import('jspdf-autotable');
      const autoTable = autoTableModule.default;
      
      const doc = new jsPDF('l', 'mm', 'a4');
      
      doc.setFontSize(20);
      doc.setTextColor(32, 33, 36);
      doc.text("Removed Assets Register (RAR)", 14, 20);
      
      doc.setFontSize(10);
      doc.setTextColor(100);
      doc.text(`Generated By: ${user?.name} | Date: ${new Date().toLocaleString()}`, 14, 28);
      
      const tableData = filtered.map(a => [
        a.assetCode,
        a.assetType,
        a.brand,
        a.model,
        a.serialNumber,
        a.purchaseDate,
        a.removalData?.adminRemovalDate || 'N/A',
        a.removalData?.reason || 'N/A',
        a.removalData?.statusToCheck || 'Archived'
      ]);

      autoTable(doc, {
        startY: 35,
        head: [['Tag', 'Category', 'Brand', 'Model', 'Serial Identity', 'Purchased', 'Removed', 'Reason', 'Final Status']],
        body: tableData,
        theme: 'grid',
        headStyles: { fillColor: [32, 33, 36], textColor: [255, 255, 255], fontStyle: 'bold' },
        styles: { fontSize: 8, cellPadding: 3 },
        alternateRowStyles: { fillColor: [248, 249, 250] }
      });
      
      doc.save(`Archived_Assets_${new Date().toISOString().split('T')[0]}.pdf`);
    } catch (err) {
      console.error("PDF Export failed:", err);
      alert("Failed to generate PDF. Check console for details.");
    } finally {
      setIsExporting(false);
    }
  };

  const handleExportSingle = async (asset: Asset) => {
    if (!asset.removalData || !canRead) return;
    setIsExporting(true);
    try {
      const { jsPDF } = await import('jspdf');
      const doc = new jsPDF('p', 'mm', 'a4');
      
      // Header Banner
      doc.setFillColor(32, 33, 36);
      doc.rect(0, 0, 210, 45, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(24);
      doc.setFont('helvetica', 'bold');
      doc.text("Asset Audit Report", 20, 28);
      
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.text(`Report Identity: ${asset.id}`, 20, 36);
      
      // Meta Data
      doc.setTextColor(32, 33, 36);
      doc.setFontSize(10);
      doc.text(`Generated: ${new Date().toLocaleString()}`, 140, 55);
      
      // Section: Technical Identification
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text("Technical Identification", 20, 65);
      doc.setDrawColor(232, 234, 237);
      doc.line(20, 68, 190, 68);
      
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text(`Asset Tag: ${asset.assetCode}`, 20, 78);
      doc.text(`Manufacturer: ${asset.brand}`, 20, 84);
      doc.text(`Model Identity: ${asset.model}`, 20, 90);
      doc.text(`Serial Identity: ${asset.serialNumber}`, 20, 96);
      doc.text(`Inventory Type: ${asset.assetType}`, 20, 102);
      doc.text(`Commission Date: ${asset.purchaseDate}`, 20, 108);

      // Section: Removal Audit
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(220, 38, 38);
      doc.text("Removal Audit Data", 20, 125);
      doc.line(20, 128, 190, 128);
      
      doc.setTextColor(32, 33, 36);
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text(`Audit Conclusion: ${asset.removalData.auditStatus}`, 20, 138);
      doc.text(`Lifecycle State: ${asset.removalData.statusToCheck}`, 20, 144);
      doc.text(`Decommission Date: ${asset.removalData.adminRemovalDate}`, 20, 150);
      doc.text(`Authorized By: ${asset.removalData.approvedBy}`, 20, 156);
      doc.text(`Financial Residual: ${settings.currencySymbol}${asset.removalData.valueAtRemoval.toLocaleString()}`, 20, 162);
      doc.text(`Unit Condition: ${asset.removalData.conditionAtRemoval}`, 20, 168);
      
      doc.setFont('helvetica', 'bold');
      doc.text("Formal Reason for Removal:", 20, 182);
      doc.setFont('helvetica', 'normal');
      const reasonLines = doc.splitTextToSize(asset.removalData.reason, 170);
      doc.text(reasonLines, 20, 188);
      
      doc.setFont('helvetica', 'bold');
      doc.text("Audit Remarks:", 20, 210);
      doc.setFont('helvetica', 'normal');
      const remarkLines = doc.splitTextToSize(asset.removalData.remark || 'No additional remarks registered.', 170);
      doc.text(remarkLines, 20, 216);

      // Footer
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text("This is an electronically generated technical audit record. Page 1 of 1", 105, 285, { align: 'center' });
      
      doc.save(`Audit_Report_${asset.assetCode}.pdf`);
    } catch (err) {
      console.error("PDF Export failed:", err);
      alert("Failed to generate PDF.");
    } finally {
      setIsExporting(false);
    }
  };

  if (!canRead) {
    return (
      <div className="flex items-center justify-center h-96">
        <div className="text-center p-12 bg-white rounded-[2.5rem] border border-red-100 shadow-xl max-w-md">
          <ShieldAlert size={64} className="mx-auto text-red-500 mb-6" />
          <h2 className="text-xl font-black text-slate-900 uppercase tracking-tighter">Access Forbidden</h2>
          <p className="text-slate-500 mt-2 font-medium">You do not have the required administrative permissions to access the Removed Assets Register.</p>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-black text-slate-900 uppercase tracking-tighter">RAR – Removed Assets Register</h1>
          <p className="text-slate-500 font-medium tracking-tight">Formal audit trail for decommissioned hardware inventory.</p>
        </div>
        <div className="flex items-center gap-3">
             <button 
                onClick={handleExportAll}
                disabled={isExporting || removedAssets.length === 0}
                className="bg-brand-primary text-white px-5 py-3 rounded-2xl flex items-center gap-3 shadow-xl hover:brightness-110 active:scale-95 transition-all disabled:opacity-50 disabled:cursor-not-allowed group"
                title="Download full register as PDF"
             >
                {isExporting ? <Loader2 size={20} className="animate-spin" /> : <Download size={20} />}
                <div className="text-left hidden sm:block">
                    <p className="text-[9px] font-black uppercase tracking-widest opacity-60 leading-none">PDF Report</p>
                    <p className="text-xs font-black leading-none mt-1">Export Register</p>
                </div>
             </button>
             <div className="bg-slate-900 text-white px-5 py-3 rounded-2xl flex items-center gap-3 shadow-xl">
                <Archive size={20} className="text-brand-primary" />
                <div className="text-right">
                    <p className="text-[9px] font-black uppercase tracking-widest opacity-60 leading-none">Total Archived</p>
                    <p className="text-lg font-black leading-none mt-1">{removedAssets.length}</p>
                </div>
             </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-4 gap-4">
        <div className="lg:col-span-2 relative">
          <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={18} />
          <input 
            type="text" 
            placeholder="Search by Tag, Brand or Model..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full pl-12 pr-4 py-3 rounded-2xl border border-slate-200 outline-none focus:ring-2 focus:ring-brand-primary bg-white text-sm font-medium shadow-sm"
          />
        </div>
        <div className="relative">
            <Filter className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={16} />
            <select 
                value={categoryFilter}
                onChange={e => setCategoryFilter(e.target.value)}
                className="w-full pl-10 pr-4 py-3 rounded-2xl border border-slate-200 outline-none focus:ring-2 focus:ring-brand-primary bg-white text-[11px] font-black uppercase tracking-widest appearance-none shadow-sm cursor-pointer"
            >
                {categories.map(c => <option key={c} value={c}>{c}</option>)}
            </select>
        </div>
        <div className="relative">
            <select 
                value={statusFilter}
                onChange={e => setStatusFilter(e.target.value)}
                className="w-full px-4 py-3 rounded-2xl border border-slate-200 outline-none focus:ring-2 focus:ring-brand-primary bg-white text-[11px] font-black uppercase tracking-widest appearance-none shadow-sm cursor-pointer"
            >
                {statuses.map(s => <option key={s} value={s}>{s}</option>)}
            </select>
            <ChevronDown className="absolute right-4 top-1/2 -translate-y-1/2 text-slate-400 pointer-events-none" size={16} />
        </div>
      </div>

      <div className="bg-white rounded-[2.5rem] border border-slate-200 shadow-sm overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left">
            <thead className="bg-slate-900 border-b border-white/5">
              <tr>
                <th className="px-6 py-5 text-[10px] font-black text-slate-400 uppercase tracking-widest">Asset Details</th>
                <th className="px-6 py-5 text-[10px] font-black text-slate-400 uppercase tracking-widest">Removal Context</th>
                <th className="px-6 py-5 text-[10px] font-black text-slate-400 uppercase tracking-widest">Audit State</th>
                <th className="px-6 py-5 text-[10px] font-black text-slate-400 uppercase tracking-widest text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {filtered.map((asset) => (
                <tr key={asset.id} className="hover:bg-slate-50 transition-colors">
                  <td className="px-6 py-4">
                    <div className="flex flex-col">
                      <span className="font-black text-slate-900 text-sm uppercase tracking-tighter">{asset.assetCode}</span>
                      <span className="text-[10px] text-slate-400 font-bold uppercase tracking-widest">{asset.brand} {asset.model}</span>
                    </div>
                  </td>
                  <td className="px-6 py-4">
                    <div className="space-y-1">
                      <p className="text-xs font-bold text-slate-700 flex items-center gap-2"><Calendar size={12} className="text-slate-300" /> {asset.removalData?.adminRemovalDate}</p>
                      <p className="text-[10px] text-slate-400 font-black uppercase tracking-widest flex items-center gap-2"><User size={12} className="text-slate-300" /> By: {asset.removalData?.approvedBy}</p>
                    </div>
                  </td>
                  <td className="px-6 py-4">
                    <span className={`px-2.5 py-1 rounded-full text-[9px] font-black uppercase tracking-widest bg-red-50 text-red-600`}>
                      {asset.removalData?.statusToCheck}
                    </span>
                  </td>
                  <td className="px-6 py-4 text-right">
                    <button 
                        onClick={() => setShowDetail(asset)}
                        className="p-3 text-brand-primary hover:bg-brand-primary hover:text-white rounded-xl transition-all shadow-sm bg-white border border-slate-100" 
                        title="View Full Audit Form"
                    >
                        <FileText size={18} />
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
          {filtered.length === 0 && (
            <div className="py-24 text-center space-y-4">
              <Archive size={48} className="mx-auto text-slate-200" />
              <p className="text-slate-400 font-bold uppercase tracking-widest text-xs italic">The register is currently empty.</p>
            </div>
          )}
        </div>
      </div>

      {/* Audit Detail Modal */}
      {showDetail && showDetail.removalData && (
        <div className="fixed inset-0 z-[300] flex items-center justify-center p-4">
          <div className="absolute inset-0 bg-slate-900/60 backdrop-blur-md" onClick={() => setShowDetail(null)} />
          <div className="relative bg-white w-full max-w-2xl rounded-[3rem] shadow-2xl p-10 border border-white/20 animate-in zoom-in overflow-y-auto max-h-[90vh]">
            <div className="flex justify-between items-start mb-10">
                <div className="flex items-center gap-4">
                    <div className="w-14 h-14 bg-red-50 text-red-600 rounded-3xl flex items-center justify-center shadow-inner">
                        <FileText size={28} />
                    </div>
                    <div>
                        <h2 className="text-2xl font-black text-slate-900 uppercase tracking-tighter leading-none">Asset Audit Report</h2>
                        <p className="text-[10px] text-slate-400 font-bold uppercase tracking-widest mt-2">Formal Decommissioning Record</p>
                    </div>
                </div>
                <button onClick={() => setShowDetail(null)} className="p-3 hover:bg-slate-100 rounded-2xl transition-all"><X size={24} /></button>
            </div>

            <div className="space-y-8">
                <section>
                    <h3 className="text-[10px] font-black text-brand-primary uppercase tracking-[0.2em] mb-4 border-b pb-2">Technical Identification</h3>
                    <div className="grid grid-cols-2 gap-y-4 gap-x-8">
                        <div>
                            <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest mb-1">Asset Tag</p>
                            <p className="font-black text-slate-900 text-sm uppercase">{showDetail.assetCode}</p>
                        </div>
                        <div>
                            <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest mb-1">Brand / Model</p>
                            <p className="font-bold text-slate-900 text-sm">{showDetail.brand} {showDetail.model}</p>
                        </div>
                        <div>
                            <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest mb-1">Serial Number</p>
                            <p className="font-mono text-xs font-bold text-slate-700">{showDetail.serialNumber}</p>
                        </div>
                        <div>
                            <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest mb-1">Category</p>
                            <p className="font-bold text-slate-900 text-sm">{showDetail.assetType}</p>
                        </div>
                    </div>
                </section>

                <section>
                    <h3 className="text-[10px] font-black text-red-600 uppercase tracking-[0.2em] mb-4 border-b pb-2">Removal Audit Data</h3>
                    <div className="grid grid-cols-2 gap-y-4 gap-x-8">
                        <div>
                            <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest mb-1">Audit Status</p>
                            <p className="font-bold text-slate-900 text-sm">{showDetail.removalData.auditStatus}</p>
                        </div>
                        <div>
                            <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest mb-1">Status To Check</p>
                            <p className="font-black text-red-600 text-sm uppercase">{showDetail.removalData.statusToCheck}</p>
                        </div>
                        <div>
                            <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest mb-1">Removal Date</p>
                            <p className="font-bold text-slate-900 text-sm">{showDetail.removalData.adminRemovalDate}</p>
                        </div>
                        <div>
                            <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest mb-1">Approved By</p>
                            <p className="font-bold text-slate-900 text-sm">{showDetail.removalData.approvedBy}</p>
                        </div>
                        <div>
                            <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest mb-1">Condition at Removal</p>
                            <p className="font-bold text-slate-900 text-sm">{showDetail.removalData.conditionAtRemoval}</p>
                        </div>
                        <div>
                            <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest mb-1">Financial Value</p>
                            <p className="font-bold text-slate-900 text-sm">{settings.currencySymbol}{showDetail.removalData.valueAtRemoval.toLocaleString()}</p>
                        </div>
                        <div className="col-span-2">
                            <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest mb-1">Reason for Removal</p>
                            <p className="font-bold text-slate-900 text-sm bg-slate-50 p-3 rounded-xl border border-slate-100">{showDetail.removalData.reason}</p>
                        </div>
                        <div className="col-span-1">
                            <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest mb-1">Proof Ref#</p>
                            <p className="font-mono text-xs font-bold text-indigo-600">{showDetail.removalData.proofRef || 'N/A'}</p>
                        </div>
                         <div className="col-span-1">
                            <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest mb-1">Last User</p>
                            <p className="font-bold text-slate-900 text-sm">{showDetail.removalData.lastKnownUserName}</p>
                        </div>
                        <div className="col-span-2">
                            <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest mb-1">Remarks</p>
                            <p className="text-sm text-slate-600 italic font-medium">"{showDetail.removalData.remark || 'No final remarks provided.'}"</p>
                        </div>
                    </div>
                </section>
            </div>

            <div className="mt-10 pt-8 border-t flex gap-4">
                <button 
                    onClick={() => handleExportSingle(showDetail)} 
                    disabled={isExporting}
                    className="flex-1 py-4 bg-slate-900 text-white rounded-2xl font-black uppercase text-xs tracking-widest flex items-center justify-center gap-2 hover:bg-black transition-all disabled:opacity-50 disabled:cursor-not-allowed"
                >
                    {isExporting ? <Loader2 size={18} className="animate-spin" /> : <Download size={18} />}
                    {isExporting ? 'Generating...' : 'Export PDF'}
                </button>
                <button 
                    onClick={() => setShowDetail(null)} 
                    className="flex-1 py-4 border-2 border-slate-100 text-slate-400 rounded-2xl font-black uppercase text-xs tracking-widest hover:bg-slate-50 transition-all"
                >
                    Close Report
                </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default RemovedAssetsRegister;
